version: '3.1'

networks:
  traefik-net:
    external: true
  zmq-net:
    external: false

services:
  requestor:
    image: xybersolve/zmq-http-req:latest
    command: npm start
    #ports:
    #  - "8686:8686"
    environment:
      ZMQ_RES_ADDRESS: tcp://responder:8672
      HTTP_PORT: "8686"
    networks:
    - traefik-net
    - zmq-net
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      labels:
      - traefik.domain=swarm.io
      - traefik.frontend.rule=PathPrefix:/ping,/reflect,/increment
      - traefik.entryPoints=http
      - traefik.backend=requestor
      - traefik.docker.network=traefik-net
      - traefik.port=8686
      - traefik.enable=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://swarm.io/ping"]
      interval: 1m
      timeout: 5s
      retries: 3

  responder:
    image: xybersolve/zmq-http-res:latest
    command: npm start
    environment:
      ZMQ_REQ_ADDRESS: "tcp://*:8672"
      ZMQ_PORT: "8672"
    networks:
    - zmq-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
